[transport]
trType = "TCP"
bufCacheSize = 64
numSharedBuf = 4096
ioUnitSize = 512

[journal]
enable = true
buffer_size_in_mb = 0
number_of_log_groups = 2
debug_mode = false
interval_in_msec_for_metric = 1000
enable_vsc = true